export type Json = string | number | boolean | null | { [key:string]: Json | undefined } | Json[];
export interface Database { public: { Tables: {
  app_settings:{Row:{created_at:string;environment:string;id:string;key:string;updated_at:string;value:Json};Insert:{created_at?:string;environment:string;id?:string;key:string;updated_at?:string;value?:Json};Update:Partial<Database['public']['Tables']['app_settings']['Insert']>;Relationships:[]};
  audit_logs:{Row:{action:string;actor_id:string|null;after_data:Json|null;before_data:Json|null;correlation_id:string|null;created_at:string;entity_id:string|null;entity_type:string;id:string;ip:string|null;metadata:Json;organization_id:string|null;user_agent:string|null};Insert:{action:string;actor_id?:string|null;after_data?:Json|null;before_data?:Json|null;correlation_id?:string;created_at?:string;entity_id?:string|null;entity_type:string;id?:string;ip?:string|null;metadata?:Json;organization_id?:string|null;user_agent?:string|null};Update:Partial<Database['public']['Tables']['audit_logs']['Insert']>;Relationships:[]};
  consents:{Row:{created_at:string;granted_at:string|null;id:string;metadata:Json;revoked_at:string|null;source:string|null;type:string;user_id:string;version:string};Insert:{created_at?:string;granted_at?:string|null;id?:string;metadata?:Json;revoked_at?:string|null;source?:string|null;type:string;user_id:string;version:string};Update:Partial<Database['public']['Tables']['consents']['Insert']>;Relationships:[]};
  feature_flags:{Row:{config:Json;created_at:string;enabled:boolean;environment:string;id:string;key:string;updated_at:string};Insert:{config?:Json;created_at?:string;environment:string;id?:string;key:string;updated_at?:string;value?:Json};Update:Partial<Database['public']['Tables']['feature_flags']['Insert']>;Relationships:[]};
  files_metadata:{Row:{created_at:string;id:string;mime:string;organization_id:string|null;owner_id:string|null;path:string;size:number;visibility:string};Insert:{created_at?:string;id?:string;mime:string;organization_id?:string|null;owner_id?:string|null;path:string;size:number;visibility:string};Update:Partial<Database['public']['Tables']['files_metadata']['Insert']>;Relationships:[]};
  guide_sections:{Row:{content:string;created_at:string;created_by:string;id:string;is_enabled:boolean;organization_id:string;property_id:string;section_type:string;sort_order:number;title:string;updated_at:string};Insert:{content?:string;created_at?:string;created_by:string;id?:string;is_enabled?:boolean;organization_id:string;property_id:string;section_type:string;sort_order?:number;title:string;updated_at?:string};Update:Partial<Database['public']['Tables']['guide_sections']['Insert']>;Relationships:[]};
  invitations:{Row:{created_at:string;email:string;expires_at:string;id:string;invited_by:string;organization_id:string;role:string;status:string;token:string};Insert:{created_at?:string;email:string;expires_at:string;id?:string;invited_by:string;organization_id:string;role?:string;status?:string;token?:string};Update:Partial<Database['public']['Tables']['invitations']['Insert']>;Relationships:[]};
  memberships:{Row:{created_at:string;id:string;organization_id:string;role:string;status:string;updated_at:string;user_id:string};Insert:{created_at?:string;id?:string;organization_id:string;role:string;status?:string;updated_at?:string;user_id:string};Update:Partial<Database['public']['Tables']['memberships']['Insert']>;Relationships:[]};
  notification_preferences:{Row:{channel:string;created_at:string;enabled:boolean;id:string;type:string;updated_at:string;user_id:string};Insert:{channel:string;created_at?:string;enabled?:boolean;id?:string;type:string;updated_at?:string;user_id:string};Update:Partial<Database['public']['Tables']['notification_preferences']['Insert']>;Relationships:[]};
  organizations:{Row:{created_at:string;id:string;name:string;status:string;type:string;updated_at:string};Insert:{created_at?:string;id?:string;name:string;status?:string;type?:string;updated_at?:string};Relationships:[]};
  profiles:{Row:{created_at:string;email:string;id:string;language:string;name:string|null;status:string;system_role:string;timezone:string;updated_at:string};Insert:{created_at?:string;email:string;id?:string;language?:string;name?:string|null;status?:string;system_role?:string;timezone?:string;updated_at?:string};Relationships:[]};
  properties:{Row:{address_line1:string|null;address_line2:string|null;bathrooms:number|null;bedrooms:number|null;city:string|null;country:string|null;created_at:string;created_by:string|null;description:string|null;id:string;latitude:number|null;longitude:number|null;max_guests:number|null;name:string;organization_id:string;postal_code:string|null;public_token:string;status:string;updated_at:string};Insert:{address_line1?:string|null;address_line2?:string|null;bathrooms?:number|null;bedrooms?:number|null;city?:string|null;country?:string|null;created_at?:string;created_by?:string|null;description?:string|null;id?:string;latitude?:number|null;longitude?:number|null;max_guests?:number|null;bedrooms?:number|null;bathrooms?:number|null;name:string;organization_id:string;postal_code?:string|null;public_token?:string;status?:string;updated_at?:string};Update:Partial<Database['public']['Tables']['properties']['Insert']>;Relationships:[]};
  property_images:{Row:{id:string;property_id:string;storage_path:string;alt_text:string|null;sort_order:number;is_primary:boolean;created_at:string;updated_at:string};Insert:{id?:string;property_id:string;storage_path:string;alt_text?:string|null;sort_order?:number;is_primary?:boolean;created_at?:string;updated_at?:string};Update:Partial<Database['public']['Tables']['property_images']['Insert']>;Relationships:[]};
  property_services:{Row:{id:string;organization_id:string;property_id:string;service_id:string;created_at:string};Insert:{id?:string;organization_id:string;property_id:string;service_id:string;created_at?:string};Update:Partial<Database['public']['Tables']['property_services']['Insert']>;Relationships:[]};
  rate_limit_events:{Row:{action:string;created_at:string;id:string;key:string;window_started_at:string};Insert:{action?:string;created_at?:string;id?:string;key:string;window_started_at:string};Update:Partial<Database['public']['Tables']['rate_limit_events']['Insert']>;Relationships:[]};
  services:{Row:{id:string;organization_id:string;created_by:string|null;name:string;description:string|null;category:string;duration_minutes:number|null;schedule_text:string|null;mode:string;capacity:number|null;location_text:string|null;cancellation_policy:string|null;status:string;created_at:string;updated_at:string};Insert:{id?:string;organization_id:string;created_by?:string|null;name:string;description?:string|null;category?:string;duration_minutes?:number|null;schedule_text?:string|null;mode?:string;capacity?:number|null;location_text?:string|null;cancellation_policy?:string|null;status?:string;created_at?:string;updated_at?:string};Update:Partial<Database['public']['Tables']['services']['Insert']>;Relationships:[]};
  user_roles:{Row:{created_at:string;id:string;status:string;system_role:string;updated_at:string;user_id:string};Insert:{created_at?:string;id?:string;status?:string;system_role:string;updated_at?:string;user_id:string};Relationships:[]};
}; Views:{}; Functions:{check_rate_limit:{Args:{max_attempts:number;rate_action:string;rate_key:string;window_seconds:number};Returns:boolean};create_invitation:{Args:{invite_email:string;invite_role?:string;target_org_id:string};Returns:Database['public']['Tables']['invitations']['Row']};get_public_property:{Args:{p_token:string};Returns:Json};has_org_role:{Args:{allowed_roles:string[];target_org_id:string};Returns:boolean};is_org_member:{Args:{target_org_id:string};Returns:boolean};record_audit_event:{Args:{event_action:string;event_after?:Json;event_before?:Json;event_correlation_id?:string;event_entity_id?:string;event_entity_type:string;event_metadata?:Json;event_organization_id?:string};Returns:Database['public']['Tables']['audit_logs']['Row']};set_membership_status:{Args:{new_status:string;target_membership_id:string};Returns:Database['public']['Tables']['memberships']['Row']};update_membership_role:{Args:{new_role:string;target_membership_id:string};Returns:Database['public']['Tables']['memberships']['Row']};set_property_status:{Args:{target_property_id:string;new_status:string};Returns:Database['public']['Tables']['properties']['Row']};}; Enums:{}; CompositeTypes:{}; }; }
