export type Json = string | number | boolean | null | { [key:string]: Json | undefined } | Json[];
type Table<R=any,I=any>={Row:R;Insert:I;Update:Partial<I>;Relationships:any[]};
type PropertyRow={id:string;organization_id:string;created_by:string|null;name:string;description:string|null;address_line1:string|null;address_line2:string|null;postal_code:string|null;city:string|null;country:string|null;latitude:number|null;longitude:number|null;max_guests:number|null;bedrooms:number|null;bathrooms:number|null;public_token:string;status:string;created_at:string;updated_at:string};
type PropertyInsert={id?:string;organization_id:string;created_by?:string|null;name:string;description?:string|null;address_line1?:string|null;address_line2?:string|null;postal_code?:string|null;city?:string|null;country?:string|null;latitude?:number|null;longitude?:number|null;max_guests?:number|null;bedrooms?:number|null;bathrooms?:number|null;public_token?:string;status?:string;created_at?:string;updated_at?:string};
type PropertyImage={id:string;property_id:string;storage_path:string;alt_text:string|null;sort_order:number;is_primary:boolean;created_at:string;updated_at:string};
type PropertyImageInsert={id?:string;property_id:string;storage_path:string;alt_text?:string|null;sort_order?:number;is_primary?:boolean;created_at?:string;updated_at?:string};
type PropertyService={id:string;organization_id:string;property_id:string;service_id:string;created_at:string};
type PropertyServiceInsert={id?:string;organization_id:string;property_id:string;service_id:string;created_at?:string};
type HostProviderConnection={id:string;host_organization_id:string;provider_id:string;requested_by:string|null;status:string;connected_at:string|null;disconnected_at:string|null;created_at:string;updated_at:string};
type HostProviderConnectionInsert={id?:string;host_organization_id:string;provider_id:string;requested_by?:string|null;status?:string;connected_at?:string|null;disconnected_at?:string;created_at?:string;updated_at?:string};
type ProviderService={id:string;provider_id:string;name:string;description:string|null;category:string;duration_minutes:number|null;price:number|null;currency:string;capacity:number|null;location_text:string|null;cancellation_policy:string|null;mode:'manual'|'api'|'google_calendar';status:'draft'|'active'|'archived';created_at:string;updated_at:string};
type ProviderServiceInsert={id?:string;provider_id:string;name:string;description?:string|null;category:string;duration_minutes?:number|null;price?:number|null;currency?:string;capacity?:number|null;location_text?:string|null;cancellation_policy?:string|null;mode?:'manual'|'api'|'google_calendar';status?:'draft'|'active'|'archived';created_at?:string;updated_at?:string};
type ServiceReservation={id:string;host_organization_id:string;provider_id:string;provider_service_id:string;requested_by:string|null;scheduled_at:string;guests_count:number;unit_price:number;currency:string;total_price:number;guest_name:string|null;guest_email:string|null;guest_phone:string|null;guest_notes:string|null;status:'pending'|'confirmed'|'declined'|'cancelled'|'completed';created_at:string;updated_at:string};
type ServiceReservationInsert={id?:string;host_organization_id:string;provider_id:string;provider_service_id:string;requested_by?:string|null;scheduled_at:string;guests_count?:number;unit_price:number;currency?:string;total_price:number;guest_name?:string|null;guest_email?:string|null;guest_phone?:string|null;guest_notes?:string|null;status?:'pending'|'confirmed'|'declined'|'cancelled'|'completed';created_at?:string;updated_at?:string};
type PublicPropertyPayload={property:{id:string;name:string;description:string|null;city:string|null;country:string|null;max_guests:number|null;bedrooms:number|null;bathrooms:number|null};images:Array<{storage_path:string;alt_text:string|null;sort_order:number;is_primary:boolean}>;guide_sections:Array<{id:string;section_type:string;title:string;content:string;sort_order:number}>;services:Array<{id:string;name:string;description:string|null;category:string;duration_minutes:number|null;schedule_text:string|null;mode:string;capacity:number|null;location_text:string|null}>};
export interface Database{public:{Tables:{app_settings:Table<any>;audit_logs:Table<any>;consents:Table<any>;feature_flags:Table<any>;files_metadata:Table<any>;guide_sections:Table<any>;host_provider_connections:Table<HostProviderConnection,HostProviderConnectionInsert>;host_provider_services:Table<any>;invitations:Table<any>;memberships:Table<any>;notification_preferences:Table<{channel:string;created_at:string;enabled:boolean;id:string;type:string;updated_at:string;user_id:string}>;organizations:Table<any>;profiles:Table<any>;properties:Table<PropertyRow,PropertyInsert>;property_images:Table<PropertyImage,PropertyImageInsert>;property_services:Table<PropertyService,PropertyServiceInsert>;provider_services:Table<ProviderService,ProviderServiceInsert>;providers:Table<any>;rate_limit_events:Table<any>;services:Table<any>;service_reservations:Table<ServiceReservation,ServiceReservationInsert>;user_roles:Table<any>};Views:{};Functions:{check_rate_limit:{Args:{max_attempts:number;rate_action:string;rate_key:string;window_seconds:number};Returns:boolean};create_invitation:{Args:{invite_email:string;invite_role?:string;target_org_id:string};Returns:any};create_public_reservation:{Args:{p_token:string;p_provider_service_id:string;p_scheduled_at:string;p_guests_count?:number;p_guest_name?:string|null;p_guest_email?:string|null;p_guest_phone?:string|null;p_guest_notes?:string|null};Returns:ServiceReservation};get_public_property:{Args:{p_token:string};Returns:PublicPropertyPayload|null};has_org_role:{Args:{allowed_roles:string[];target_org_id:string};Returns:boolean};is_org_member:{Args:{target_org_id:string};Returns:boolean};record_audit_event:{Args:{event_action:string;event_after?:Json;event_before?:Json;event_correlation_id?:string;event_entity_id?:string;event_entity_type:string;event_metadata?:Json;event_organization_id?:string};Returns:any};set_membership_status:{Args:{new_status:string;target_membership_id:string};Returns:any};update_membership_role:{Args:{new_role:string;target_membership_id:string};Returns:any};set_membership_status:{Args:{new_status:string;target_membership_id:string};Returns:any};set_property_status:{Args:{target_property_id:string;new_status:string};Returns:any}};Enums:{};CompositeTypes:{}}}