import {useEffect,useState} from 'react';
import HostShell from './HostShell';
import Properties from './Properties';
import {supabase} from '../lib/supabase';

type Props={org:{id:string;name:string;type:string;status:string};session:any;onSignOut:()=>void};
export default function HostDashboard({org,session,onSignOut}:Props){
 const [active,setActive]=useState('dashboard'); const [memberCount,setMemberCount]=useState(0);
 useEffect(()=>{if(!supabase)return;supabase.from('memberships').select('id',{count:'exact',head:true}).eq('organization_id',org.id).eq('status','active').then(({count})=>setMemberCount(count??0));},[org.id]);
 const dashboard=<div className="host-content"><section className="host-welcome"><div><p className="host-eyebrow">Dashboard Hôte</p><h2>Bonjour 👋</h2><p className="host-muted">Pilotez votre activité depuis <strong>{org.name}</strong>.</p></div><button className="host-primary" onClick={()=>setActive('properties')}>+ Ajouter un logement</button></section><section className="host-kpis"><div className="host-kpi"><span>Logements actifs</span><strong>0</strong><small>Aucun logement publié</small></div><div className="host-kpi"><span>Réservations à venir</span><strong>0</strong><small>En attente de votre activité</small></div><div className="host-kpi"><span>Services réservés</span><strong>0</strong><small>Aucune réservation</small></div><div className="host-kpi"><span>Membres actifs</span><strong>{memberCount}</strong><small>Dans votre organisation</small></div></section><section className="host-grid"><div className="host-panel"><div className="host-panel-head"><div><p className="host-eyebrow">Séjours</p><h3>Prochains check-in / check-out</h3></div><button className="host-link" onClick={()=>setActive('reservations')}>Voir les réservations</button></div><div className="host-empty"><strong>Aucun séjour à afficher</strong>Ajoutez votre premier logement pour commencer à recevoir et gérer des réservations.</div></div><div className="host-panel"><div className="host-panel-head"><div><p className="host-eyebrow">Actions rapides</p><h3>Commencer avec Holly Buddy</h3></div></div><div className="host-actions"><button className="host-action" onClick={()=>setActive('properties')}><strong>Ajouter un logement</strong><span>Informations, photos et publication</span></button><button className="host-action" onClick={()=>setActive('services')}><strong>Configurer les services</strong><span>Créer votre catalogue d'activités</span></button><button className="host-action" onClick={()=>setActive('guide')}><strong>Préparer le guide client</strong><span>Construire l'expérience du séjour</span></button><button className="host-action" onClick={()=>setActive('users')}><strong>Gérer les utilisateurs</strong><span>{memberCount} membre{memberCount>1?'s':''} actif{memberCount>1?'s':''}</span></button></div></div></section><section className="host-panel"><div className="host-panel-head"><div><p className="host-eyebrow">Activité</p><h3>Dernières activités</h3></div></div><div className="host-empty"><strong>Votre activité apparaîtra ici</strong>Les actions métier seront historisées au fur et à mesure de la construction des modules.</div></section></div>;
 const placeholder=<div className="host-content"><section className="host-welcome"><div><p className="host-eyebrow">Holly Buddy Host Platform</p><h2>Module en construction</h2><p className="host-muted">Cette section est réservée au vrai module métier. Aucune donnée fictive n'est affichée.</p></div></section><div className="host-panel"><div className="host-empty"><strong>{active}</strong>Le module sera connecté à son modèle de données réel avant d'être considéré comme fonctionnel.</div></div></div>;
 return <HostShell organizationName={org.name} active={active} onNavigate={setActive} onSignOut={onSignOut}>{active==='dashboard'?dashboard:active==='properties'?<Properties orgId={org.id} userId={session.user.id}/>:placeholder}</HostShell>;
}
