import {useEffect,useState} from 'react';
import {supabase} from '../lib/supabase';
type Property={id:string;name:string;status:string;city:string|null;country:string|null;max_guests:number|null;bedrooms:number|null; bathrooms:number|null;description:string|null};
type Props={orgId:string;userId:string};
export default function Properties({orgId,userId}:Props){
 const [items,setItems]=useState<Property[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[open,setOpen]=useState(false),[error,setError]=useState('');
 const [form,setForm]=useState({name:'',description:'',city:'',country:'',max_guests:'',bedrooms:'',bathrooms:''});
 const load=async()=>{if(!supabase)return;setLoading(true);const {data,error}=await supabase.from('properties').select('id,name,status,city,country,max_guests,bedrooms,bathrooms,description').eq('organization_id',orgId).order('created_at',{ascending:false});if(error)setError(error.message);else setItems((data as Property[])??[]);setLoading(false)};
 useEffect(()=>{load()},[orgId]);
 const create=async(e:React.FormEvent)=>{e.preventDefault();if(!supabase)return;setSaving(true);setError('');const {error}=await supabase.from('properties').insert({organization_id:orgId,created_by:userId,name:form.name.trim(),description:form.description.trim()||null,city:form.city.trim()||null,country:form.country.trim()||null,max_guests:form.max_guests?Number(form.max_guests):null,bedrooms:form.bedrooms?Number(form.bedrooms):null,bathrooms:form.bathrooms?Number(form.bathrooms):null});if(error)setError(error.message);else{setForm({name:'',description:'',city:'',country:'',max_guests:'',bedrooms:'',bathrooms:''});setOpen(false);await load()}setSaving(false)};
 return <div className="host-content"><section className="host-welcome"><div><p className="host-eyebrow">EXPLOITATION</p><h2>Mes logements</h2><p className="host-muted">Gérez les logements de votre organisation.</p></div><button className="host-primary" onClick={()=>setOpen(true)}>+ Ajouter un logement</button></section>{error&&<div className="message">{error}</div>}{loading?<div className="host-panel"><div className="host-empty">Chargement…</div></div>:items.length===0?<div className="host-panel"><div className="host-empty"><strong>Aucun logement</strong><span>Créez votre premier logement.</span></div></div>:<div className="property-grid">{items.map(p=><article className="property-card" key={p.id}><div className="property-cover">{p.status==='active'?'Publié':'Brouillon'}</div><div className="property-body"><div><h3>{p.name}</h3><p>{[p.city,p.country].filter(Boolean).join(', ')||'Localisation à compléter'}</p></div><div className="property-meta"><span>{p.max_guests??'—'} voyageurs</span><span>{p.bedrooms??'—'} chambres</span><span>{p.bathrooms??'—'} sdb</span></div></div></article>)}</div>}{open&&<div className="modal-backdrop"><div className="modal-card"><div className="host-panel-head"><div><p className="host-eyebrow">NOUVEAU LOGEMENT</p><h3>Créer un logement</h3></div><button className="host-link" type="button" onClick={()=>setOpen(false)}>Fermer</button></div><form className="property-form" onSubmit={create}><label>Nom du logement<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label>Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} rows={4}/></label><div className="form-row"><label>Ville<input value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></label><label>Pays<input value={form.country} onChange={e=>setForm({...form,country:e.target.value})}/></label></div><div className="form-row three"><label>Voyageurs<input type="number" min="1" value={form.max_guests} onChange={e=>setForm({...form,max_guests:e.target.value})}/></label><label>Chambres<input type="number" min="0" value={form.bedrooms} onChange={e=>setForm({...form,bedrooms:e.target.value})}/></label><label>Salles de bain<input type="number" min="0" step="0.5" value={form.bathrooms} onChange={e=>setForm({...form,bathrooms:e.target.value})}/></label></div><button className="host-primary" disabled={saving}>{saving?'Création…':'Créer le logement'}</button></form></div></div>}</div>;
}
