import { StrictMode,useEffect,useState } from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';
import {isSupabaseConfigured,supabase} from './lib/supabase';
import {DEV_TEST_MODE,DEV_TEST_USER} from './devTest';
import HostDashboard from './host/HostDashboard';

type Mode='login'|'signup'|'recovery-request'|'recovery'; type Org={id:string;name:string;type:string;status:string}; type Member={id:string;user_id:string;role:string;status:string;profiles?:{email?:string;name?:string|null}|null}; type Invite={id:string;email:string;role:string;status:string;expires_at:string};
const labels:Record<string,string>={owner:'Owner',admin:'Admin',member:'Member',viewer:'Viewer'};
function App(){
 const inviteToken=new URLSearchParams(window.location.search).get('invite');
 const recoveryHash=new URLSearchParams(window.location.hash.replace(/^#/, '')).get('type')==='recovery';
 const [session,setSession]=useState<any>(null),[org,setOrg]=useState<Org|null>(null),[mode,setMode]=useState<Mode>(recoveryHash?'recovery':'login'),[view,setView]=useState<'dashboard'|'users'>('dashboard'),[testMode,setTestMode]=useState(false);
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[newPassword,setNewPassword]=useState(''),[orgName,setOrgName]=useState('');
 const [members,setMembers]=useState<Member[]>([]),[invites,setInvites]=useState<Invite[]>([]),[inviteEmail,setInviteEmail]=useState(''),[inviteRole,setInviteRole]=useState('member');
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[accepting,setAccepting]=useState(false),[accepted,setAccepted]=useState(false),[status,setStatus]=useState('checking');
 useEffect(()=>{if(!supabase){setStatus('not-configured');return}supabase.auth.getSession().then(({data,error})=>{setSession(data.session);setStatus(error?'error':'connected')});const {data:l}=supabase.auth.onAuthStateChange((event,s)=>{setSession(s);if(event==='PASSWORD_RECOVERY')setMode('recovery')});return()=>l.subscription.unsubscribe()},[]);
 useEffect(()=>{if(!supabase||!session?.user?.id)return;supabase.from('memberships').select('organization_id,organizations(id,name,type,status)').eq('user_id',session.user.id).eq('status','active').limit(1).maybeSingle().then(({data})=>setOrg((data as any)?.organizations??null))},[session]);
 const loadUsers=async()=>{if(!supabase||!org)return;const {data,error}=await supabase.from('memberships').select('id,user_id,role,status,profiles(email,name)').eq('organization_id',org.id).order('created_at');if(!error)setMembers((data as any[])??[]);const {data:iv}=await supabase.from('invitations').select('id,email,role,status,expires_at').eq('organization_id',org.id).eq('status','pending').order('created_at',{ascending:false});setInvites(iv??[])};
 useEffect(()=>{if(org&&view==='users')loadUsers()},[org,view]);
 const acceptInvitation=async()=>{if(!supabase||!inviteToken){setMessage('Lien d’invitation invalide.');return}if(!session){setMessage('Connecte-toi avec l’adresse e-mail qui a reçu l’invitation.');return}setAccepting(true);setMessage('');const r=await fetch(`${import.meta.env.VITE_SUPABASE_URL}/functions/v1/accept-invitation`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${(await supabase.auth.getSession()).data.session?.access_token}`},body:JSON.stringify({token:inviteToken})});const p=await r.json().catch(()=>({}));if(r.ok){setAccepted(true);setMessage('Invitation acceptée. Ton accès est maintenant actif.');window.history.replaceState({},'',window.location.pathname)}else setMessage(p.error||'Impossible d’accepter cette invitation.');setAccepting(false)};
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!supabase)return;setBusy(true);setMessage('');if(mode==='signup'){const {data,error}=await supabase.auth.signUp({email,password,options:{data:{name},emailRedirectTo:window.location.origin}});if(error)setMessage(error.message);else setMessage(data.session?'Compte créé.':'Vérifie ton e-mail pour confirmer ton compte.')}else if(mode==='login'){const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setMessage(error.message)}else{const {error}=await supabase.auth.updateUser({password:newPassword});if(error)setMessage(error.message);else{await supabase.auth.signOut();setSession(null);setMode('login');setMessage('Mot de passe mis à jour.')}}setBusy(false)};
 const recovery=async(e:React.FormEvent)=>{e.preventDefault();if(!supabase)return;setBusy(true);const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:window.location.origin});setMessage(error?error.message:'Lien envoyé. Vérifie ton e-mail.');setBusy(false)};
 const createOrg=async(e:React.FormEvent)=>{e.preventDefault();if(!supabase)return;setBusy(true);const s=(await supabase.auth.getSession()).data.session;if(!s){setMessage('Session expirée.');setBusy(false);return}const r=await fetch(`${import.meta.env.VITE_SUPABASE_URL}/functions/v1/create-organization`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${s.access_token}`},body:JSON.stringify({name:orgName,type:'host'})});const p=await r.json().catch(()=>({}));if(r.ok){setOrg(p.organization);setOrgName('');setMessage('Organisation créée.')}else setMessage(p.error||'Impossible de créer l’organisation.');setBusy(false)};
 const createInvite=async(e:React.FormEvent)=>{e.preventDefault();if(!supabase||!org)return;setBusy(true);const {error}=await supabase.rpc('create_invitation',{target_org_id:org.id,invite_email:inviteEmail,invite_role:inviteRole});setMessage(error?error.message:'Invitation créée. L’e-mail sera envoyé quand le SMTP sera configuré.');if(!error){setInviteEmail('');await loadUsers()}setBusy(false)};
 const revoke=async(id:string)=>{if(!supabase||!org)return;setBusy(true);const {error}=await supabase.from('invitations').update({status:'revoked'}).eq('id',id).eq('organization_id',org.id);setMessage(error?error.message:'Invitation révoquée.');await loadUsers();setBusy(false)};
 const changeRole=async(id:string,role:string)=>{if(!supabase||!org)return;setBusy(true);const {error}=await supabase.rpc('update_membership_role',{target_membership_id:id,new_role:role});setMessage(error?error.message:'Rôle mis à jour.');await loadUsers();setBusy(false)};
 const changeStatus=async(id:string,statusValue:string)=>{if(!supabase||!org)return;setBusy(true);const {error}=await supabase.rpc('set_membership_status',{target_membership_id:id,new_status:statusValue});setMessage(error?error.message:'Accès mis à jour.');await loadUsers();setBusy(false)};
 const signOut=async()=>{if(supabase)await supabase.auth.signOut();setSession(null);setOrg(null);setView('dashboard');setTestMode(false)};
 if(!isSupabaseConfigured)return <main className="app-shell"><section className="foundation-card"><p className="eyebrow">Foundation</p><h1>Holly Buddy</h1><p>Supabase environment variables pending.</p></section></main>;
 if(testMode)return <main className="dashboard-shell"><header className="topbar"><div className="brand"><span className="brand-mark">H</span><div><strong>Holly Buddy</strong><span>Mode test</span></div></div><div className="topbar-actions"><span className="status compact"><span className="status-dot"/>MODE TEST</span><button className="text-button" onClick={()=>setTestMode(false)}>Quitter le test</button></div></header><div className="dashboard-content"><section className="hero"><div><p className="eyebrow">Environnement de test</p><h1>Bienvenue 👋</h1><p className="muted">Interface de démonstration sans session Supabase réelle.</p></div><div className="organization-badge"><span>Utilisateur test</span><strong>{DEV_TEST_USER.name}</strong><small>{DEV_TEST_USER.email}</small></div></section><section className="stats-grid"><div className="stat-card"><span>Organisation</span><strong>1</strong><small>Demo Organization</small></div><div className="stat-card"><span>Utilisateurs</span><strong>4</strong><small>Exemple de rôles</small></div><div className="stat-card"><span>Sécurité</span><strong>TEST</strong><small>Aucune donnée sensible</small></div></section></div></main>;
 if(inviteToken&&!accepted)return <main className="app-shell"><section className="auth-card"><p className="eyebrow">Holly Buddy</p><h1>Invitation</h1><p className="muted">Tu as reçu une invitation à rejoindre une organisation Holly Buddy.</p>{session?<><p className="muted">Connecté avec <strong>{session.user.email}</strong>.</p><button className="button" onClick={acceptInvitation} disabled={accepting}>{accepting?'Acceptation…':'Accepter l’invitation'}</button></>:<><p className="muted">Connecte-toi avec l’adresse e-mail destinataire de l’invitation.</p><form onSubmit={submit}><label>E-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Mot de passe<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button className="button" disabled={busy}>{busy?'Connexion…':'Se connecter et accepter'}</button></form><button className="switch" onClick={()=>setMode('signup')}>Créer un compte</button></>}{message&&<div className="message">{message}</div>}<div className="status status-connected"><span className="status-dot"/> Supabase connected</div></section></main>;
 if(mode==='recovery')return <main className="app-shell"><section className="auth-card"><p className="eyebrow">Holly Buddy</p><h1>Nouveau mot de passe</h1><form onSubmit={submit}><label>Nouveau mot de passe<input type="password" value={newPassword} onChange={e=>setNewPassword(e.target.value)} minLength={6} required/></label><button className="button" disabled={busy}>Définir le nouveau mot de passe</button></form>{message&&<div className="message">{message}</div>}</section></main>;
 if(session&&org)return <HostDashboard org={org} session={session} onSignOut={signOut}/>;
 if(session)return <main className="app-shell"><section className="dashboard-card"><p className="eyebrow">Holly Buddy</p><h1>Bienvenue 👋</h1><p className="muted">Tu es connecté avec {session.user.email}.</p><div className="organization-panel"><h2>Créer ton organisation</h2><form onSubmit={createOrg}><label>Nom<input value={orgName} onChange={e=>setOrgName(e.target.value)} minLength={2} maxLength={120} required/></label><button className="button" disabled={busy}>Créer l’organisation</button></form></div>{message&&<div className="message">{message}</div>}<button className="button secondary" onClick={signOut}>Se déconnecter</button></section></main>;
 if(mode==='recovery-request')return <main className="app-shell"><section className="auth-card"><p className="eyebrow">Holly Buddy</p><h1>Mot de passe oublié ?</h1><form onSubmit={recovery}><label>E-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><button className="button" disabled={busy}>Envoyer le lien</button></form>{message&&<div className="message">{message}</div>}<button className="switch" onClick={()=>setMode('login')}>Retour</button></section></main>;
 return <main className="app-shell"><section className="auth-card"><p className="eyebrow">Holly Buddy</p><h1>{mode==='login'?'Connexion':'Créer ton compte'}</h1><p className="muted">La fondation est prête.</p><form onSubmit={submit}>{mode==='signup'&&<label>Nom<input value={name} onChange={e=>setName(e.target.value)} required/></label>}<label>E-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Mot de passe<input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={6} required/></label><button className="button" disabled={busy}>{busy?'Chargement…':mode==='login'?'Se connecter':'Créer le compte'}</button></form>{message&&<div className="message">{message}</div>}<button className="switch" onClick={()=>{setMode(mode==='login'?'signup':'login');setMessage('')}}>{mode==='login'?'Pas encore de compte ? Créer un compte':'Déjà un compte ? Se connecter'}</button>{mode==='login'&&<button className="switch" onClick={()=>setMode('recovery-request')}>Mot de passe oublié ?</button>}<div className={`status status-${status}`}><span className="status-dot"/>{status==='connected'?'Supabase connected':'Vérification Supabase…'}</div></section></main>;
}
createRoot(document.getElementById('root')!).render(<StrictMode><App/></StrictMode>);