import { StrictMode,useEffect,useState } from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';
import {isSupabaseConfigured,supabase} from './lib/supabase';
import HostDashboard from './host/HostDashboard';
import ProviderPortal from './provider/ProviderPortal';
import PublicProperty from './client/PublicProperty';

type Mode='login'|'signup'|'recovery-request'|'recovery'; type Org={id:string;name:string;type:string;status:string};
type Provider={id:string;profile_code:string;business_name:string;public_name:string|null;description:string|null;email:string|null;phone:string|null;website:string|null;city:string|null;region:string|null;country:string|null;status:string};
type Workspace='choose'|'host'|'provider';
function App(){
 const publicMatch=window.location.pathname.match(/^\/p\/([^/]+)\/?$/); if(publicMatch)return <PublicProperty token={publicMatch[1]}/>;
 const recoveryHash=new URLSearchParams(window.location.hash.replace(/^#/, '')).get('type')==='recovery';
 const [session,setSession]=useState<any>(null),[org,setOrg]=useState<Org|null>(null),[provider,setProvider]=useState<Provider|null>(null),[workspace,setWorkspace]=useState<Workspace>('choose'),[mode,setMode]=useState<Mode>(recoveryHash?'recovery':'login');
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[newPassword,setNewPassword]=useState(''),[orgName,setOrgName]=useState('');
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[status,setStatus]=useState('checking');
 useEffect(()=>{if(!supabase){setStatus('not-configured');return}supabase.auth.getSession().then(({data,error})=>{setSession(data.session);setStatus(error?'error':'connected')});const {data:l}=supabase.auth.onAuthStateChange((event,s)=>{setSession(s);if(event==='PASSWORD_RECOVERY')setMode('recovery')});return()=>l.subscription.unsubscribe()},[]);
 useEffect(()=>{if(!supabase||!session?.user?.id)return;let cancelled=false;const load=async()=>{const [membershipResult,providerResult]=await Promise.all([supabase.from('memberships').select('organization_id,organizations(id,name,type,status)').eq('user_id',session.user.id).eq('status','active').limit(1).maybeSingle(),supabase.from('providers').select('id,profile_code,business_name,public_name,description,email,phone,website,city,region,country,status').eq('owner_user_id',session.user.id).eq('status','active').limit(1).maybeSingle()]);if(cancelled)return;setOrg((membershipResult.data as any)?.organizations??null);setProvider((providerResult.data as Provider|null)??null)};load();return()=>{cancelled=true}},[session]);
 useEffect(()=>{if(!session){setWorkspace('choose');return}if(provider&&!org)setWorkspace('provider');else if(org&&!provider)setWorkspace('host');else if(!provider&&!org)setWorkspace('choose')},[session,provider,org]);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!supabase)return;setBusy(true);setMessage('');if(mode==='signup'){const {data,error}=await supabase.auth.signUp({email,password,options:{data:{name},emailRedirectTo:window.location.origin}});if(error)setMessage(error.message);else setMessage(data.session?'Compte créé.':'Vérifie ton e-mail pour confirmer ton compte.')}else if(mode==='login'){const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setMessage(error.message)}else{const {error}=await supabase.auth.updateUser({password:newPassword});if(error)setMessage(error.message);else{await supabase.auth.signOut();setSession(null);setMode('login');setMessage('Mot de passe mis à jour.')}}setBusy(false)};
 const recovery=async(e:React.FormEvent)=>{e.preventDefault();if(!supabase)return;setBusy(true);const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:window.location.origin});setMessage(error?error.message:'Lien envoyé. Vérifie ton e-mail.');setBusy(false)};
 const createOrg=async(e:React.FormEvent)=>{e.preventDefault();if(!supabase)return;setBusy(true);const s=(await supabase.auth.getSession()).data.session;if(!s){setMessage('Session expirée.');setBusy(false);return}const r=await fetch(`${import.meta.env.VITE_SUPABASE_URL}/functions/v1/create-organization`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${s.access_token}`},body:JSON.stringify({name:orgName,type:'host'})});const p=await r.json().catch(()=>({}));if(r.ok){setOrg(p.organization);setOrgName('');setMessage('Organisation créée.')}else setMessage(p.error||'Impossible de créer l’organisation.');setBusy(false)};
 const signOut=async()=>{if(supabase)await supabase.auth.signOut();setSession(null);setOrg(null);setProvider(null);setWorkspace('choose')};
 if(!isSupabaseConfigured)return <main className="app-shell"><section className="auth-card"><p className="eyebrow">Foundation</p><h1>Holly Buddy</h1><p>Supabase environment variables pending.</p></section></main>;
 if(mode==='recovery')return <main className="app-shell"><section className="auth-card"><p className="eyebrow">Holly Buddy</p><h1>Nouveau mot de passe</h1><form onSubmit={submit}><label>Nouveau mot de passe<input type="password" value={newPassword} onChange={e=>setNewPassword(e.target.value)} minLength={6} required/></label><button className="button" disabled={busy}>Définir le nouveau mot de passe</button></form>{message&&<div className="message">{message}</div>}</section></main>;
 if(session&&provider&&org&&workspace==='choose')return <main className="app-shell"><section className="dashboard-card"><p className="eyebrow">Holly Buddy</p><h1>Choisir votre espace</h1><p className="muted">Ce compte possède un espace hôte et un profil prestataire.</p><div className="role-choice"><button className="role-card" onClick={()=>setWorkspace('host')}><strong>Espace hôte</strong><span>{org.name}</span></button><button className="role-card" onClick={()=>setWorkspace('provider')}><strong>Espace prestataire</strong><span>{provider.public_name||provider.business_name}</span></button></div><button className="button secondary" onClick={signOut}>Se déconnecter</button></section></main>;
 if(session&&provider&&workspace==='provider')return <ProviderPortal provider={provider} onSignOut={signOut} onSwitchToHost={org?()=>setWorkspace('host'):undefined}/>;
 if(session&&org&&workspace==='host')return <HostDashboard org={org} session={session} onSignOut={signOut}/>;
 if(session)return <main className="app-shell"><section className="dashboard-card"><p className="eyebrow">Holly Buddy</p><h1>Bienvenue 👋</h1><p className="muted">Tu es connecté avec {session.user.email}.</p><div className="organization-panel"><h2>Créer ton organisation</h2><form onSubmit={createOrg}><label>Nom<input value={orgName} onChange={e=>setOrgName(e.target.value)} minLength={2} maxLength={120} required/></label><button className="button" disabled={busy}>{busy?'Création…':'Créer l’organisation'}</button></form></div>{message&&<div className="message">{message}</div>}<button className="button secondary" onClick={signOut}>Se déconnecter</button></section></main>;
 if(mode==='recovery-request')return <main className="app-shell"><section className="auth-card"><p className="eyebrow">Holly Buddy</p><h1>Mot de passe oublié ?</h1><form onSubmit={recovery}><label>E-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><button className="button" disabled={busy}>Envoyer le lien</button></form>{message&&<div className="message">{message}</div>}<button className="switch" onClick={()=>setMode('login')}>Retour</button></section></main>;
 return <main className="app-shell"><section className="auth-card"><p className="eyebrow">Holly Buddy</p><h1>{mode==='login'?'Connexion':'Créer ton compte'}</h1><p className="muted">La fondation est prête.</p><form onSubmit={submit}>{mode==='signup'&&<label>Nom<input value={name} onChange={e=>setName(e.target.value)} required/></label>}<label>E-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Mot de passe<input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={6} required/></label><button className="button" disabled={busy}>{busy?'Chargement…':mode==='login'?'Se connecter':'Créer le compte'}</button></form>{message&&<div className="message">{message}</div>}<button className="switch" onClick={()=>{setMode(mode==='login'?'signup':'login');setMessage('')}}>{mode==='login'?'Pas encore de compte ? Créer un compte':'Déjà un compte ? Se connecter'}</button>{mode==='login'&&<button className="switch" onClick={()=>setMode('recovery-request')}>Mot de passe oublié ?</button>}<div className={`status status-${status}`}><span className="status-dot"/>{status==='connected'?'Supabase connected':'Vérification Supabase…'}</div></section></main>;
}
createRoot(document.getElementById('root')!).render(<StrictMode><App/></StrictMode>);
