import {useEffect,useState} from 'react';
import {supabase} from '../lib/supabase';

type Service={id:string;name:string;description:string|null;category:string;duration_minutes:number|null;price:number|null;currency:string;mode:'manual'|'api'|'google_calendar';capacity:number|null;location_text:string|null;cancellation_policy:string|null;status:'draft'|'active'|'archived'};
type Props={providerId:string};

const emptyService:Omit<Service,'id'>={name:'',description:null,category:'',duration_minutes:null,price:null,currency:'CHF',mode:'manual',capacity:null,location_text:null,cancellation_policy:null,status:'draft'};

export default function ProviderServices({providerId}:Props){
 const [services,setServices]=useState<Service[]>([]);const [form,setForm]=useState(emptyService);const [open,setOpen]=useState(false);const [editing,setEditing]=useState<string|null>(null);const [message,setMessage]=useState('');const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);
 const load=async()=>{if(!supabase){setLoading(false);setMessage('Supabase n’est pas configuré sur ce déploiement.');return}setLoading(true);const {data,error}=await supabase.from('provider_services').select('*').eq('provider_id',providerId).order('created_at',{ascending:false});if(error){setMessage(`Impossible de charger les services : ${error.message}`);setLoading(false);return}setServices((data??[]) as Service[]);setLoading(false)};
 useEffect(()=>{void load()},[providerId]);
 const save=async()=>{if(form.name.trim().length<2||!form.category.trim()){setMessage('Indiquez au minimum un nom et une catégorie.');return}if(!supabase){setMessage('Supabase n’est pas configuré sur ce déploiement.');return}setSaving(true);setMessage('');const payload={...form,name:form.name.trim(),category:form.category.trim()};const result=editing?await supabase.from('provider_services').update(payload).eq('id',editing).eq('provider_id',providerId):await supabase.from('provider_services').insert({provider_id:providerId,...payload});if(result.error){setMessage(`Impossible d’enregistrer le service : ${result.error.message}`);setSaving(false);return}setMessage(editing?'Service modifié.':'Service créé.');setForm(emptyService);setEditing(null);setOpen(false);await load();setSaving(false)};
 const edit=(s:Service)=>{setForm({name:s.name,description:s.description,category:s.category,duration_minutes:s.duration_minutes,price:s.price,currency:s.currency,mode:s.mode,capacity:s.capacity,location_text:s.location_text,cancellation_policy:s.cancellation_policy,status:s.status});setEditing(s.id);setOpen(true);setMessage('')};
 const archive=async(id:string)=>{if(!supabase)return;const {error}=await supabase.from('provider_services').update({status:'archived'}).eq('id',id).eq('provider_id',providerId);if(error){setMessage(`Impossible d’archiver le service : ${error.message}`);return}await load()};
 const toggle=async(s:Service)=>{if(!supabase)return;const {error}=await supabase.from('provider_services').update({status:s.status==='active'?'draft':'active'}).eq('id',s.id).eq('provider_id',providerId);if(error){setMessage(`Impossible de modifier le statut : ${error.message}`);return}await load()};
 return <section className="provider-card"><div className="provider-card-head"><div><p className="provider-eyebrow">CATALOGUE</p><h2>Services</h2><p>Gérez les prestations proposées aux hôtes connectés.</p></div><button type="button" onClick={()=>{setForm(emptyService);setEditing(null);setOpen(true);setMessage('')}}>Ajouter un service</button></div>
  {loading?<div className="provider-empty"><span>Chargement des services…</span></div>:services.length===0?<div className="provider-empty"><strong>Aucun service configuré</strong><span>Ajoutez votre première prestation.</span></div>:<div className="provider-connections">{services.map(s=><div className="provider-connection" key={s.id}><div><strong>{s.name}</strong><span>{s.category}{s.price!=null?` · ${s.price} ${s.currency}`:''}{s.duration_minutes?` · ${s.duration_minutes} min`:''}</span><small>{s.status==='active'?'Actif':s.status==='archived'?'Archivé':'Brouillon'}</small></div><div className="provider-actions">{s.status!=='archived'&&<button type="button" onClick={()=>void toggle(s)}>{s.status==='active'?'Désactiver':'Activer'}</button>}{s.status!=='archived'&&<button type="button" onClick={()=>edit(s)}>Modifier</button>}{s.status!=='archived'&&<button type="button" onClick={()=>void archive(s.id)}>Archiver</button>}</div></div>)}</div>}
  {message&&<div className="provider-message">{message}</div>}
  {open&&<div className="provider-modal-backdrop"><div className="provider-modal"><div className="provider-card-head"><div><p className="provider-eyebrow">SERVICE</p><h2>{editing?'Modifier le service':'Ajouter un service'}</h2></div><button type="button" onClick={()=>setOpen(false)}>Fermer</button></div><div className="provider-form-grid"><label>Nom<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Ex. Transfert aéroport"/></label><label>Catégorie<input value={form.category} onChange={e=>setForm({...form,category:e.target.value})} placeholder="Transport"/></label><label>Description<textarea value={form.description??''} onChange={e=>setForm({...form,description:e.target.value||null})}/></label><label>Prix<input type="number" min="0" step="0.01" value={form.price??''} onChange={e=>setForm({...form,price:e.target.value===''?null:Number(e.target.value)})}/></label><label>Devise<select value={form.currency} onChange={e=>setForm({...form,currency:e.target.value})}><option>CHF</option><option>EUR</option><option>USD</option></select></label><label>Durée (minutes)<input type="number" min="1" value={form.duration_minutes??''} onChange={e=>setForm({...form,duration_minutes:e.target.value===''?null:Number(e.target.value)})}/></label><label>Capacité<input type="number" min="1" value={form.capacity??''} onChange={e=>setForm({...form,capacity:e.target.value===''?null:Number(e.target.value)})}/></label><label>Lieu<input value={form.location_text??''} onChange={e=>setForm({...form,location_text:e.target.value||null})} placeholder="Genève"/></label><label>Politique d’annulation<textarea value={form.cancellation_policy??''} onChange={e=>setForm({...form,cancellation_policy:e.target.value||null})}/></label></div><div className="provider-modal-actions"><button type="button" onClick={()=>setOpen(false)}>Annuler</button><button type="button" onClick={()=>void save()} disabled={saving}>{saving?'Enregistrement…':'Enregistrer'}</button></div></div></div>}
 </section>;
}
